using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.SqlClient;

namespace QLDSV1
{
    public partial class DiemSinhVien : DevExpress.XtraEditors.XtraForm
    {
        DiemSinhVienDAL dal;
        DataConnection dc;
        public DiemSinhVien()
        {
            InitializeComponent();
            dal = new DiemSinhVienDAL();
            dc = new DataConnection();
            // This line of code is generated by Data Source Configuration Wizard
            monhocTableAdapter1.Fill(ds1.MONHOC);
        }
        public bool CheckData()
        {
            if (string.IsNullOrEmpty(txtmonhoc.Text)||string.IsNullOrEmpty(txtlanthi.Text)|| string.IsNullOrEmpty(txtlop.Text)|| int.Parse(txtlanthi.Text) >2)
            {
                MessageBox.Show("Bạn chưa nhập lần thi hoặc môn học", "Thông Báo", MessageBoxButtons.OK, MessageBoxIcon.Information);
                //int lan = int.Parse(lanthi);
                txtmonhoc.Focus();
                txtlanthi.Focus();
                return false;
            }
            return true;
        }
        public bool IsNumber(string pValue)
        {
            foreach (Char c in pValue)
            {
                if (!Char.IsDigit(c))
                    return false;
            }
            return true;
        }
        public void ShowDanhSachSV(string malop,string mamh,int lanthi)
        {
            DataTable dt = dal.getDanhSachSV(malop,mamh,lanthi);
            tableDiem.DataSource = dt;

        }

        private void DiemSinhVien_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'ds1.LOP' table. You can move, or remove it, as needed.
            this.lOPTableAdapter.Connection.ConnectionString = Program.connstr;
            ds1.EnforceConstraints = false;
            this.lOPTableAdapter.Fill(this.ds1.LOP);
            // TODO: This line of code loads data into the 'qLDSVDataSet1.V_DS_PHANMANH2' table. You can move, or remove it, as needed.
            this.v_DS_PHANMANH2TableAdapter.Fill(this.qLDSVDataSet1.V_DS_PHANMANH2);
            btnSave.Enabled = false;
            cmbDiem.SelectedIndex = -1;
            cmbDiem.SelectedIndex = Program.temp;
            simpleButton1.Enabled = false;
            if (Program.mGroup.Equals("KHOA"))
            {
                cmbDiem.Enabled = false;
            }
        }

        private void BarButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if(CheckData())
            {
                string malop = txtlop.Text;
                string mamh = txtmonhoc.EditValue.ToString();
                int lanthi = int.Parse(txtlanthi.Text);
                ShowDanhSachSV(malop,mamh,lanthi);
                btnSave.Enabled = false;
                string notice = "" + Program.demrow;
                simpleButton1.Enabled = true;
            }
            
            //MessageBox.Show(notice);
        }

        private void BarButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            DataConnection dc = new DataConnection();
            SqlConnection con = dc.getConnect();
            con.Open();
            SqlTransaction t = con.BeginTransaction();
            try
            {
                int lanthi=int.Parse(txtlanthi.Text);
                
                for (int i = 0; i < Program.demrow; i++)
                {
    
                    int index = -1;
                    index = i;
                    BeanDiemSV dsv = new BeanDiemSV();
                    dsv.MASV = gridView1.GetRowCellValue(index, "MASV").ToString();

                    dsv.MAMH = txtmonhoc.EditValue.ToString();

                    dsv.DIEM = gridView1.GetRowCellValue(index, "DIEM").ToString();
                    if (lanthi == 1)
                    {
                        if(dal.checkDiemSV(dsv.MASV,dsv.MAMH,1)>0 && dal.checkDiemSV(dsv.MASV, dsv.MAMH, 2)==0)
                        {
                            dsv.LANTHI = int.Parse(txtlanthi.Text)+1;
                            dal.InsertDiem(dsv,con,t);
                           // MessageBox.Show("Lưu lại thành công");
                        }
                        else if(dal.checkDiemSV(dsv.MASV, dsv.MAMH, 1) > 0 && dal.checkDiemSV(dsv.MASV, dsv.MAMH, 2) > 0)
                        {
                            MessageBox.Show("Không thể lưu sinh viên này"+dsv.MASV);
                        }
                        else
                        {
                            dsv.LANTHI = int.Parse(txtlanthi.Text);
                            dal.InsertDiem(dsv,con,t);
                            //MessageBox.Show("Lưu lại thành công");
                        }
                    }
                    if(lanthi==2)
                    {
                        if (dal.checkDiemSV(dsv.MASV, dsv.MAMH, 1) > 0 && dal.checkDiemSV(dsv.MASV, dsv.MAMH, 2) == 0)
                        {
                            dsv.LANTHI = int.Parse(txtlanthi.Text);
                            dal.InsertDiem(dsv,con,t);
                            //MessageBox.Show("Lưu lại thành công");
                        }
                        else if (dal.checkDiemSV(dsv.MASV, dsv.MAMH, 1) > 0 && dal.checkDiemSV(dsv.MASV, dsv.MAMH, 2) > 0)
                        {
                            MessageBox.Show("Không thể lưu sinh viên này" + dsv.MASV);
                        }
                        else if(dal.checkDiemSV(dsv.MASV, dsv.MAMH, 1) == 0)
                        {
                            
                            //dsv.LANTHI = int.Parse(txtlanthi.Text);
   
                            //dal.InsertDiem(dsv,con,t);

                            //dsv.LANTHI = int.Parse(txtlanthi.Text)-1;
                            //dsv.DIEM = "0";
                            //dal.InsertDiem(dsv);
                            MessageBox.Show("Không thể lưu");
                        }

                    }
                    

                }
                t.Commit();
                MessageBox.Show("Lưu lại thành công");
                btnSave.Enabled = false;
            }
            catch (Exception)
            {
                t.Rollback();
                MessageBox.Show("Lỗi");
            }
           

        }

        private void SimpleButton1_Click(object sender, EventArgs e)
        {
            //MessageBox.Show("Nhấn lưu lại để lưu");
            //btnSave.Enabled = true;
            int dem = 0;
            
            string mamh = txtmonhoc.EditValue.ToString();
            int lanthi = int.Parse(txtlanthi.Text);
            string notice = "";
            string notice3 = "Các sinh viên sau đây đã có điểm môn " +mamh+" lần " + 1 +" nếu lưu lại điểm tự động chuyển lần 2  : ";
            string notice1 = "Các sinh viên sau đây đã có điểm môn " + mamh + " lần 1 và 2 nên sẽ không thể lưu sinh viên này : ";
            string notice2 = "Các sinh viên sau đây chưa có điểm lần 1 nên không thể lưu lần 2: ";
            for (int i = 0; i < Program.demrow; i++)
            {
                int index = -1;
                index = i;
                BeanDiemSV dsv = new BeanDiemSV();
                string masv = gridView1.GetRowCellValue(index, "MASV").ToString();

                
                string string_diem = gridView1.GetRowCellValue(index, "DIEM").ToString();
                if(string.IsNullOrEmpty(string_diem))
                {
                    MessageBox.Show("Vui lòng nhập giá trị");
                    btnSave.Enabled = false;
                    break;
                }
                else
                {
                    double diem = Convert.ToDouble(string_diem);
                    if (diem < 0 || diem > 10)
                    {
                        MessageBox.Show("Bạn nhập giá trị điểm không hợp lệ vui lòng kiểm tra lại trước khi lưu");
                        btnSave.Enabled = false;
                        break;
                    }
                    else
                    {
                        if(lanthi==1)
                        {
                            dem++;
                            if (dal.checkDiemSV(masv, mamh, 1) > 0 && dal.checkDiemSV(masv, mamh, 2) == 0)
                            {
                                notice3 += masv + ",";
                                //notice = notice3;
                            }
                            else if (dal.checkDiemSV(masv, mamh, 1) > 0 && dal.checkDiemSV(masv, mamh, 2) > 0)
                            {
                                dem--;
                                notice1 += masv + " " + ";";
                                
                            }
                            
                        }
                        if(lanthi==2)
                        {
                            //dem++;
                            if (dal.checkDiemSV(masv, mamh, 1) > 0 && dal.checkDiemSV(masv, mamh, 2) > 0)
                            {
                                notice1 += masv + " " + ";";
                                //notice = notice1;
                            }
                            else if (dal.checkDiemSV(masv, mamh, 1)==0)
                            {
                                
                                notice2 += masv + " " + ";";
                                //btnSave.Enabled = false;
                            }
                            else if(dal.checkDiemSV(masv, mamh, 1) > 0 && dal.checkDiemSV(masv, mamh, 2) == 0)
                            {
                                dem++;
                            }
                        }
                        
                    }

                    
                }
                

            }
            if(dem== Program.demrow)
            {

                btnSave.Enabled = true;
            }
            if (lanthi == 1) MessageBox.Show(notice1 + "\n" + notice3);
            if (lanthi == 2) MessageBox.Show(notice1 + "\n" + notice2);
        }

        private void CmbDiem_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (Program.mGroup.Equals("PGV"))
            {
                try
                {
                    Program.servername = cmbDiem.SelectedValue.ToString();
                    if (Program.servername.Equals(Program.tenServerDN))
                    {
                        Program.mlogin = Program.mloginDN;
                        Program.password = Program.passwordDN;
                        DataConnection dc = new DataConnection();
                        dal = new DiemSinhVienDAL();
                        
                        this.lOPTableAdapter.Connection.ConnectionString = Program.connstr;
                 
                        this.lOPTableAdapter.Fill(this.ds1.LOP);
                    }
                    else
                    {
                        Program.mlogin = Program.remotelogin;
                        Program.password = Program.remotepassword;
                        DataConnection dc = new DataConnection();
                        //MessageBox.Show(Program.servername);
                        
                        dal = new DiemSinhVienDAL();
                        this.lOPTableAdapter.Connection.ConnectionString = Program.connstr;

                        this.lOPTableAdapter.Fill(this.ds1.LOP);
                    }
                       
                }
                catch (Exception)
                {


                }
            }
        }

        private void BarButtonItem2_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            formUpdateDiem frm = new formUpdateDiem();
            //frm.MdiParent = this;
            frm.Show();
        }

        private void TableDiem_Click(object sender, EventArgs e)
        {

        }
    }
}